/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackagesOffersRouteImport } from './routes/packages-offers'
import { Route as NearbyAttractionsRouteImport } from './routes/nearby-attractions'
import { Route as LocationRouteImport } from './routes/location'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesOffersRoute = PackagesOffersRouteImport.update({
  id: '/packages-offers',
  path: '/packages-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyAttractionsRoute = NearbyAttractionsRouteImport.update({
  id: '/nearby-attractions',
  path: '/nearby-attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoomsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/packages-offers': typeof PackagesOffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/packages-offers': typeof PackagesOffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/packages-offers': typeof PackagesOffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/location'
    | '/nearby-attractions'
    | '/packages-offers'
    | '/privacy-policy'
    | '/reviews'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/rooms/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/location'
    | '/nearby-attractions'
    | '/packages-offers'
    | '/privacy-policy'
    | '/reviews'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/rooms/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/location'
    | '/nearby-attractions'
    | '/packages-offers'
    | '/privacy-policy'
    | '/reviews'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/rooms/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  LocationRoute: typeof LocationRoute
  NearbyAttractionsRoute: typeof NearbyAttractionsRoute
  PackagesOffersRoute: typeof PackagesOffersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages-offers': {
      id: '/packages-offers'
      path: '/packages-offers'
      fullPath: '/packages-offers'
      preLoaderRoute: typeof PackagesOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby-attractions': {
      id: '/nearby-attractions'
      path: '/nearby-attractions'
      fullPath: '/nearby-attractions'
      preLoaderRoute: typeof NearbyAttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface RoomsRouteChildren {
  RoomsSlugRoute: typeof RoomsSlugRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsSlugRoute: RoomsSlugRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  FacilitiesRoute: FacilitiesRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  LocationRoute: LocationRoute,
  NearbyAttractionsRoute: NearbyAttractionsRoute,
  PackagesOffersRoute: PackagesOffersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  RoomsRoute: RoomsRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
