/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ShimlaTravelGuideRouteImport } from './routes/shimla-travel-guide'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackagesOffersRouteImport } from './routes/packages-offers'
import { Route as NearbyAttractionsRouteImport } from './routes/nearby-attractions'
import { Route as LocationRouteImport } from './routes/location'
import { Route as HotelNearTheRidgeShimlaRouteImport } from './routes/hotel-near-the-ridge-shimla'
import { Route as HotelNearShimlaRailwayStationRouteImport } from './routes/hotel-near-shimla-railway-station'
import { Route as HotelNearShimlaRouteImport } from './routes/hotel-near-shimla'
import { Route as HotelNearScandalPointShimlaRouteImport } from './routes/hotel-near-scandal-point-shimla'
import { Route as HotelNearLakkarBazaarShimlaRouteImport } from './routes/hotel-near-lakkar-bazaar-shimla'
import { Route as HotelNearKufriRouteImport } from './routes/hotel-near-kufri'
import { Route as HotelNearJakhuTempleShimlaRouteImport } from './routes/hotel-near-jakhu-temple-shimla'
import { Route as HotelNearChristChurchShimlaRouteImport } from './routes/hotel-near-christ-church-shimla'
import { Route as HotelInMallRoadRouteImport } from './routes/hotel-in-mall-road'
import { Route as HotelInBudgetShimlaRouteImport } from './routes/hotel-in-budget-shimla'
import { Route as HotelAtMallRoadRouteImport } from './routes/hotel-at-mall-road'
import { Route as HotelAtKufriRouteImport } from './routes/hotel-at-kufri'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FamilyHotelInShimlaRouteImport } from './routes/family-hotel-in-shimla'
import { Route as FamilyHotelRouteImport } from './routes/family-hotel'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BudgetHotelRouteImport } from './routes/budget-hotel'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BestHotelAtKufriRouteImport } from './routes/best-hotel-at-kufri'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as LocationsMallRoadRouteImport } from './routes/locations.mall-road'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AttractionsKufriRouteImport } from './routes/attractions.kufri'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShimlaTravelGuideRoute = ShimlaTravelGuideRouteImport.update({
  id: '/shimla-travel-guide',
  path: '/shimla-travel-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesOffersRoute = PackagesOffersRouteImport.update({
  id: '/packages-offers',
  path: '/packages-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyAttractionsRoute = NearbyAttractionsRouteImport.update({
  id: '/nearby-attractions',
  path: '/nearby-attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelNearTheRidgeShimlaRoute = HotelNearTheRidgeShimlaRouteImport.update({
  id: '/hotel-near-the-ridge-shimla',
  path: '/hotel-near-the-ridge-shimla',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelNearShimlaRailwayStationRoute =
  HotelNearShimlaRailwayStationRouteImport.update({
    id: '/hotel-near-shimla-railway-station',
    path: '/hotel-near-shimla-railway-station',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelNearShimlaRoute = HotelNearShimlaRouteImport.update({
  id: '/hotel-near-shimla',
  path: '/hotel-near-shimla',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelNearScandalPointShimlaRoute =
  HotelNearScandalPointShimlaRouteImport.update({
    id: '/hotel-near-scandal-point-shimla',
    path: '/hotel-near-scandal-point-shimla',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelNearLakkarBazaarShimlaRoute =
  HotelNearLakkarBazaarShimlaRouteImport.update({
    id: '/hotel-near-lakkar-bazaar-shimla',
    path: '/hotel-near-lakkar-bazaar-shimla',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelNearKufriRoute = HotelNearKufriRouteImport.update({
  id: '/hotel-near-kufri',
  path: '/hotel-near-kufri',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelNearJakhuTempleShimlaRoute =
  HotelNearJakhuTempleShimlaRouteImport.update({
    id: '/hotel-near-jakhu-temple-shimla',
    path: '/hotel-near-jakhu-temple-shimla',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelNearChristChurchShimlaRoute =
  HotelNearChristChurchShimlaRouteImport.update({
    id: '/hotel-near-christ-church-shimla',
    path: '/hotel-near-christ-church-shimla',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelInMallRoadRoute = HotelInMallRoadRouteImport.update({
  id: '/hotel-in-mall-road',
  path: '/hotel-in-mall-road',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelInBudgetShimlaRoute = HotelInBudgetShimlaRouteImport.update({
  id: '/hotel-in-budget-shimla',
  path: '/hotel-in-budget-shimla',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelAtMallRoadRoute = HotelAtMallRoadRouteImport.update({
  id: '/hotel-at-mall-road',
  path: '/hotel-at-mall-road',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelAtKufriRoute = HotelAtKufriRouteImport.update({
  id: '/hotel-at-kufri',
  path: '/hotel-at-kufri',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyHotelInShimlaRoute = FamilyHotelInShimlaRouteImport.update({
  id: '/family-hotel-in-shimla',
  path: '/family-hotel-in-shimla',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyHotelRoute = FamilyHotelRouteImport.update({
  id: '/family-hotel',
  path: '/family-hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetHotelRoute = BudgetHotelRouteImport.update({
  id: '/budget-hotel',
  path: '/budget-hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BestHotelAtKufriRoute = BestHotelAtKufriRouteImport.update({
  id: '/best-hotel-at-kufri',
  path: '/best-hotel-at-kufri',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoomsRoute,
} as any)
const LocationsMallRoadRoute = LocationsMallRoadRouteImport.update({
  id: '/locations/mall-road',
  path: '/locations/mall-road',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AttractionsKufriRoute = AttractionsKufriRouteImport.update({
  id: '/attractions/kufri',
  path: '/attractions/kufri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/best-hotel-at-kufri': typeof BestHotelAtKufriRoute
  '/blog': typeof BlogRouteWithChildren
  '/budget-hotel': typeof BudgetHotelRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/family-hotel': typeof FamilyHotelRoute
  '/family-hotel-in-shimla': typeof FamilyHotelInShimlaRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hotel-at-kufri': typeof HotelAtKufriRoute
  '/hotel-at-mall-road': typeof HotelAtMallRoadRoute
  '/hotel-in-budget-shimla': typeof HotelInBudgetShimlaRoute
  '/hotel-in-mall-road': typeof HotelInMallRoadRoute
  '/hotel-near-christ-church-shimla': typeof HotelNearChristChurchShimlaRoute
  '/hotel-near-jakhu-temple-shimla': typeof HotelNearJakhuTempleShimlaRoute
  '/hotel-near-kufri': typeof HotelNearKufriRoute
  '/hotel-near-lakkar-bazaar-shimla': typeof HotelNearLakkarBazaarShimlaRoute
  '/hotel-near-scandal-point-shimla': typeof HotelNearScandalPointShimlaRoute
  '/hotel-near-shimla': typeof HotelNearShimlaRoute
  '/hotel-near-shimla-railway-station': typeof HotelNearShimlaRailwayStationRoute
  '/hotel-near-the-ridge-shimla': typeof HotelNearTheRidgeShimlaRoute
  '/location': typeof LocationRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/packages-offers': typeof PackagesOffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/restaurant': typeof RestaurantRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/shimla-travel-guide': typeof ShimlaTravelGuideRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/attractions/kufri': typeof AttractionsKufriRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/mall-road': typeof LocationsMallRoadRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/best-hotel-at-kufri': typeof BestHotelAtKufriRoute
  '/blog': typeof BlogRouteWithChildren
  '/budget-hotel': typeof BudgetHotelRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/family-hotel': typeof FamilyHotelRoute
  '/family-hotel-in-shimla': typeof FamilyHotelInShimlaRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hotel-at-kufri': typeof HotelAtKufriRoute
  '/hotel-at-mall-road': typeof HotelAtMallRoadRoute
  '/hotel-in-budget-shimla': typeof HotelInBudgetShimlaRoute
  '/hotel-in-mall-road': typeof HotelInMallRoadRoute
  '/hotel-near-christ-church-shimla': typeof HotelNearChristChurchShimlaRoute
  '/hotel-near-jakhu-temple-shimla': typeof HotelNearJakhuTempleShimlaRoute
  '/hotel-near-kufri': typeof HotelNearKufriRoute
  '/hotel-near-lakkar-bazaar-shimla': typeof HotelNearLakkarBazaarShimlaRoute
  '/hotel-near-scandal-point-shimla': typeof HotelNearScandalPointShimlaRoute
  '/hotel-near-shimla': typeof HotelNearShimlaRoute
  '/hotel-near-shimla-railway-station': typeof HotelNearShimlaRailwayStationRoute
  '/hotel-near-the-ridge-shimla': typeof HotelNearTheRidgeShimlaRoute
  '/location': typeof LocationRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/packages-offers': typeof PackagesOffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/restaurant': typeof RestaurantRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/shimla-travel-guide': typeof ShimlaTravelGuideRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/attractions/kufri': typeof AttractionsKufriRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/mall-road': typeof LocationsMallRoadRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/best-hotel-at-kufri': typeof BestHotelAtKufriRoute
  '/blog': typeof BlogRouteWithChildren
  '/budget-hotel': typeof BudgetHotelRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/family-hotel': typeof FamilyHotelRoute
  '/family-hotel-in-shimla': typeof FamilyHotelInShimlaRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hotel-at-kufri': typeof HotelAtKufriRoute
  '/hotel-at-mall-road': typeof HotelAtMallRoadRoute
  '/hotel-in-budget-shimla': typeof HotelInBudgetShimlaRoute
  '/hotel-in-mall-road': typeof HotelInMallRoadRoute
  '/hotel-near-christ-church-shimla': typeof HotelNearChristChurchShimlaRoute
  '/hotel-near-jakhu-temple-shimla': typeof HotelNearJakhuTempleShimlaRoute
  '/hotel-near-kufri': typeof HotelNearKufriRoute
  '/hotel-near-lakkar-bazaar-shimla': typeof HotelNearLakkarBazaarShimlaRoute
  '/hotel-near-scandal-point-shimla': typeof HotelNearScandalPointShimlaRoute
  '/hotel-near-shimla': typeof HotelNearShimlaRoute
  '/hotel-near-shimla-railway-station': typeof HotelNearShimlaRailwayStationRoute
  '/hotel-near-the-ridge-shimla': typeof HotelNearTheRidgeShimlaRoute
  '/location': typeof LocationRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/packages-offers': typeof PackagesOffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/restaurant': typeof RestaurantRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/shimla-travel-guide': typeof ShimlaTravelGuideRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/attractions/kufri': typeof AttractionsKufriRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/mall-road': typeof LocationsMallRoadRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/best-hotel-at-kufri'
    | '/blog'
    | '/budget-hotel'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/family-hotel'
    | '/family-hotel-in-shimla'
    | '/faq'
    | '/gallery'
    | '/hotel-at-kufri'
    | '/hotel-at-mall-road'
    | '/hotel-in-budget-shimla'
    | '/hotel-in-mall-road'
    | '/hotel-near-christ-church-shimla'
    | '/hotel-near-jakhu-temple-shimla'
    | '/hotel-near-kufri'
    | '/hotel-near-lakkar-bazaar-shimla'
    | '/hotel-near-scandal-point-shimla'
    | '/hotel-near-shimla'
    | '/hotel-near-shimla-railway-station'
    | '/hotel-near-the-ridge-shimla'
    | '/location'
    | '/nearby-attractions'
    | '/packages-offers'
    | '/privacy-policy'
    | '/restaurant'
    | '/reviews'
    | '/rooms'
    | '/shimla-travel-guide'
    | '/terms-and-conditions'
    | '/attractions/kufri'
    | '/blog/$slug'
    | '/locations/mall-road'
    | '/rooms/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/best-hotel-at-kufri'
    | '/blog'
    | '/budget-hotel'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/family-hotel'
    | '/family-hotel-in-shimla'
    | '/faq'
    | '/gallery'
    | '/hotel-at-kufri'
    | '/hotel-at-mall-road'
    | '/hotel-in-budget-shimla'
    | '/hotel-in-mall-road'
    | '/hotel-near-christ-church-shimla'
    | '/hotel-near-jakhu-temple-shimla'
    | '/hotel-near-kufri'
    | '/hotel-near-lakkar-bazaar-shimla'
    | '/hotel-near-scandal-point-shimla'
    | '/hotel-near-shimla'
    | '/hotel-near-shimla-railway-station'
    | '/hotel-near-the-ridge-shimla'
    | '/location'
    | '/nearby-attractions'
    | '/packages-offers'
    | '/privacy-policy'
    | '/restaurant'
    | '/reviews'
    | '/rooms'
    | '/shimla-travel-guide'
    | '/terms-and-conditions'
    | '/attractions/kufri'
    | '/blog/$slug'
    | '/locations/mall-road'
    | '/rooms/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/best-hotel-at-kufri'
    | '/blog'
    | '/budget-hotel'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/family-hotel'
    | '/family-hotel-in-shimla'
    | '/faq'
    | '/gallery'
    | '/hotel-at-kufri'
    | '/hotel-at-mall-road'
    | '/hotel-in-budget-shimla'
    | '/hotel-in-mall-road'
    | '/hotel-near-christ-church-shimla'
    | '/hotel-near-jakhu-temple-shimla'
    | '/hotel-near-kufri'
    | '/hotel-near-lakkar-bazaar-shimla'
    | '/hotel-near-scandal-point-shimla'
    | '/hotel-near-shimla'
    | '/hotel-near-shimla-railway-station'
    | '/hotel-near-the-ridge-shimla'
    | '/location'
    | '/nearby-attractions'
    | '/packages-offers'
    | '/privacy-policy'
    | '/restaurant'
    | '/reviews'
    | '/rooms'
    | '/shimla-travel-guide'
    | '/terms-and-conditions'
    | '/attractions/kufri'
    | '/blog/$slug'
    | '/locations/mall-road'
    | '/rooms/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BestHotelAtKufriRoute: typeof BestHotelAtKufriRoute
  BlogRoute: typeof BlogRouteWithChildren
  BudgetHotelRoute: typeof BudgetHotelRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FamilyHotelRoute: typeof FamilyHotelRoute
  FamilyHotelInShimlaRoute: typeof FamilyHotelInShimlaRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HotelAtKufriRoute: typeof HotelAtKufriRoute
  HotelAtMallRoadRoute: typeof HotelAtMallRoadRoute
  HotelInBudgetShimlaRoute: typeof HotelInBudgetShimlaRoute
  HotelInMallRoadRoute: typeof HotelInMallRoadRoute
  HotelNearChristChurchShimlaRoute: typeof HotelNearChristChurchShimlaRoute
  HotelNearJakhuTempleShimlaRoute: typeof HotelNearJakhuTempleShimlaRoute
  HotelNearKufriRoute: typeof HotelNearKufriRoute
  HotelNearLakkarBazaarShimlaRoute: typeof HotelNearLakkarBazaarShimlaRoute
  HotelNearScandalPointShimlaRoute: typeof HotelNearScandalPointShimlaRoute
  HotelNearShimlaRoute: typeof HotelNearShimlaRoute
  HotelNearShimlaRailwayStationRoute: typeof HotelNearShimlaRailwayStationRoute
  HotelNearTheRidgeShimlaRoute: typeof HotelNearTheRidgeShimlaRoute
  LocationRoute: typeof LocationRoute
  NearbyAttractionsRoute: typeof NearbyAttractionsRoute
  PackagesOffersRoute: typeof PackagesOffersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RestaurantRoute: typeof RestaurantRoute
  ReviewsRoute: typeof ReviewsRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  ShimlaTravelGuideRoute: typeof ShimlaTravelGuideRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AttractionsKufriRoute: typeof AttractionsKufriRoute
  LocationsMallRoadRoute: typeof LocationsMallRoadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shimla-travel-guide': {
      id: '/shimla-travel-guide'
      path: '/shimla-travel-guide'
      fullPath: '/shimla-travel-guide'
      preLoaderRoute: typeof ShimlaTravelGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages-offers': {
      id: '/packages-offers'
      path: '/packages-offers'
      fullPath: '/packages-offers'
      preLoaderRoute: typeof PackagesOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby-attractions': {
      id: '/nearby-attractions'
      path: '/nearby-attractions'
      fullPath: '/nearby-attractions'
      preLoaderRoute: typeof NearbyAttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-the-ridge-shimla': {
      id: '/hotel-near-the-ridge-shimla'
      path: '/hotel-near-the-ridge-shimla'
      fullPath: '/hotel-near-the-ridge-shimla'
      preLoaderRoute: typeof HotelNearTheRidgeShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-shimla-railway-station': {
      id: '/hotel-near-shimla-railway-station'
      path: '/hotel-near-shimla-railway-station'
      fullPath: '/hotel-near-shimla-railway-station'
      preLoaderRoute: typeof HotelNearShimlaRailwayStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-shimla': {
      id: '/hotel-near-shimla'
      path: '/hotel-near-shimla'
      fullPath: '/hotel-near-shimla'
      preLoaderRoute: typeof HotelNearShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-scandal-point-shimla': {
      id: '/hotel-near-scandal-point-shimla'
      path: '/hotel-near-scandal-point-shimla'
      fullPath: '/hotel-near-scandal-point-shimla'
      preLoaderRoute: typeof HotelNearScandalPointShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-lakkar-bazaar-shimla': {
      id: '/hotel-near-lakkar-bazaar-shimla'
      path: '/hotel-near-lakkar-bazaar-shimla'
      fullPath: '/hotel-near-lakkar-bazaar-shimla'
      preLoaderRoute: typeof HotelNearLakkarBazaarShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-kufri': {
      id: '/hotel-near-kufri'
      path: '/hotel-near-kufri'
      fullPath: '/hotel-near-kufri'
      preLoaderRoute: typeof HotelNearKufriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-jakhu-temple-shimla': {
      id: '/hotel-near-jakhu-temple-shimla'
      path: '/hotel-near-jakhu-temple-shimla'
      fullPath: '/hotel-near-jakhu-temple-shimla'
      preLoaderRoute: typeof HotelNearJakhuTempleShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-christ-church-shimla': {
      id: '/hotel-near-christ-church-shimla'
      path: '/hotel-near-christ-church-shimla'
      fullPath: '/hotel-near-christ-church-shimla'
      preLoaderRoute: typeof HotelNearChristChurchShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-in-mall-road': {
      id: '/hotel-in-mall-road'
      path: '/hotel-in-mall-road'
      fullPath: '/hotel-in-mall-road'
      preLoaderRoute: typeof HotelInMallRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-in-budget-shimla': {
      id: '/hotel-in-budget-shimla'
      path: '/hotel-in-budget-shimla'
      fullPath: '/hotel-in-budget-shimla'
      preLoaderRoute: typeof HotelInBudgetShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-at-mall-road': {
      id: '/hotel-at-mall-road'
      path: '/hotel-at-mall-road'
      fullPath: '/hotel-at-mall-road'
      preLoaderRoute: typeof HotelAtMallRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-at-kufri': {
      id: '/hotel-at-kufri'
      path: '/hotel-at-kufri'
      fullPath: '/hotel-at-kufri'
      preLoaderRoute: typeof HotelAtKufriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-hotel-in-shimla': {
      id: '/family-hotel-in-shimla'
      path: '/family-hotel-in-shimla'
      fullPath: '/family-hotel-in-shimla'
      preLoaderRoute: typeof FamilyHotelInShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-hotel': {
      id: '/family-hotel'
      path: '/family-hotel'
      fullPath: '/family-hotel'
      preLoaderRoute: typeof FamilyHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-hotel': {
      id: '/budget-hotel'
      path: '/budget-hotel'
      fullPath: '/budget-hotel'
      preLoaderRoute: typeof BudgetHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-hotel-at-kufri': {
      id: '/best-hotel-at-kufri'
      path: '/best-hotel-at-kufri'
      fullPath: '/best-hotel-at-kufri'
      preLoaderRoute: typeof BestHotelAtKufriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/locations/mall-road': {
      id: '/locations/mall-road'
      path: '/locations/mall-road'
      fullPath: '/locations/mall-road'
      preLoaderRoute: typeof LocationsMallRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/attractions/kufri': {
      id: '/attractions/kufri'
      path: '/attractions/kufri'
      fullPath: '/attractions/kufri'
      preLoaderRoute: typeof AttractionsKufriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface RoomsRouteChildren {
  RoomsSlugRoute: typeof RoomsSlugRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsSlugRoute: RoomsSlugRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BestHotelAtKufriRoute: BestHotelAtKufriRoute,
  BlogRoute: BlogRouteWithChildren,
  BudgetHotelRoute: BudgetHotelRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  FacilitiesRoute: FacilitiesRoute,
  FamilyHotelRoute: FamilyHotelRoute,
  FamilyHotelInShimlaRoute: FamilyHotelInShimlaRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HotelAtKufriRoute: HotelAtKufriRoute,
  HotelAtMallRoadRoute: HotelAtMallRoadRoute,
  HotelInBudgetShimlaRoute: HotelInBudgetShimlaRoute,
  HotelInMallRoadRoute: HotelInMallRoadRoute,
  HotelNearChristChurchShimlaRoute: HotelNearChristChurchShimlaRoute,
  HotelNearJakhuTempleShimlaRoute: HotelNearJakhuTempleShimlaRoute,
  HotelNearKufriRoute: HotelNearKufriRoute,
  HotelNearLakkarBazaarShimlaRoute: HotelNearLakkarBazaarShimlaRoute,
  HotelNearScandalPointShimlaRoute: HotelNearScandalPointShimlaRoute,
  HotelNearShimlaRoute: HotelNearShimlaRoute,
  HotelNearShimlaRailwayStationRoute: HotelNearShimlaRailwayStationRoute,
  HotelNearTheRidgeShimlaRoute: HotelNearTheRidgeShimlaRoute,
  LocationRoute: LocationRoute,
  NearbyAttractionsRoute: NearbyAttractionsRoute,
  PackagesOffersRoute: PackagesOffersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RestaurantRoute: RestaurantRoute,
  ReviewsRoute: ReviewsRoute,
  RoomsRoute: RoomsRouteWithChildren,
  ShimlaTravelGuideRoute: ShimlaTravelGuideRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AttractionsKufriRoute: AttractionsKufriRoute,
  LocationsMallRoadRoute: LocationsMallRoadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
